language: ruby
rvm:
  - 1.9.3
gemfile: spec/dummy/Gemfile
before_install:
  - gem update --system
before_script: ci/solr.sh
script: "RAILS_VERSION=rails3 BUNDLE_GEMFILE=gemfiles/rails3 bundle exec rake spec"