development:
  solr:
    hostname: localhost
    port: 8983
    log_level: INFO
    auto_commit_after_request: false

test:
  solr:
    hostname: localhost
    port: 8984
    log_level: WARNING
    auto_commit_after_request: false
